### PR TITLE
Change to html

### PR DESCRIPTION
**Pull request by Wjplatformer**
# DEVXAN
I have worked for 150 minutes on this<br>
two reasons why you need this good website
- Most scratchers don't know how to use github and can be greeted by this website if needed
- A dog will [tear your stuffed monke on your profile picture if you don't merge it](https://www.youtube.com/watch?v=LqWo-ZIhaic) and Nax will steal your oreos

### CODE REVIEW

**Comment by Wjplatformer** [comment]
Please come online @devxan I am genuinely worried for you :frowning:

**Comment by devxan** [comment]
Hmmm 🤔

**Comment by Wjplatformer** [comment]
Where have you been @devxan ? You've been offline for 2 days. Anyways I am holidaying.

**Comment by devxan** [comment]
> Where have you been? You've been offline for 2 days

School's ending, so I no longer have a laptop & I don't check my email as much on my phone.

**Comment by Wjplatformer** [comment]
Oh, so your laptop is provided by your school. I see. Well, won't disturb you until summer is over. (July or August)

**Comment by devxan** [comment]
> Oh, so your laptop is provided by your school. I see. Well, won't disturb you until summer is over. (July or August)

You can still use my GitHub profile repo's discussions! I still have my phone... @Wjplatformer

**Comment by Wjplatformer** [comment]
Alright then :)

**Pull request merged**
