### PR TITLE
Ready for PR

### PR DESCRIPTION
**Pull request by Wjplatformer**
# Some improvements :P
Such as:
- addition of description
- and the classic badge
- and credits!

### CODE REVIEW

**Comment by Wjplatformer** [comment]
Got PR explanation from [here](https://www.youtube.com/watch?v=8A4TsoXJOs8). Hope this is useful!

**Review by devxan — CHANGES_REQUESTED** [review]
I like it besides this spacing 
image
and this spacing: 
image

**Comment by Wjplatformer** [comment]
okie. No spacing then

**Comment by Wjplatformer** [comment]
Okay. Deleted the second whitespace. However the first one is natural and there are no breaks! :confused:

**Comment by Wjplatformer** [comment]
Wait. Did you mean the border:question: Or the whitespace:grey_question:

**Comment by devxan** [comment]
I feel like this pull request isn't needed, sorry. But great job figuring out how they work! I know that it took me a long while to learn that 😵

**Comment by Wjplatformer** [comment]
Alright then. Thank you for actively reviewing it!

**Pull request closed without merging**
